/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayFair.java
 *
 * Created on Jun 14, 2018, 11:13:51 AM
 */

package Project_Playfair;

/**
 *
 * @author Heni
 */
import KP;
import java.awt.Dimension;
import java.awt.Toolkit;
public class PlayFair extends javax.swing.JFrame {

    /** Creates new form PlayFair */
    public PlayFair() {
        initComponents();
            centeredWindow();
    }
private void centeredWindow(){
        // Get the size of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        // Determine the new location of the window
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        // Move the window
        setLocation(x, y);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        encrypt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        encrypt1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        eplain = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ecipher = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dcipher = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        dplain = new javax.swing.JTextArea();
        encrypt2 = new javax.swing.JButton();
        encrypt3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        m34 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        m22 = new javax.swing.JTextField();
        m43 = new javax.swing.JTextField();
        key = new javax.swing.JTextField();
        m21 = new javax.swing.JTextField();
        m02 = new javax.swing.JTextField();
        m20 = new javax.swing.JTextField();
        m01 = new javax.swing.JTextField();
        m42 = new javax.swing.JTextField();
        m41 = new javax.swing.JTextField();
        m44 = new javax.swing.JTextField();
        m40 = new javax.swing.JTextField();
        m24 = new javax.swing.JTextField();
        m23 = new javax.swing.JTextField();
        m32 = new javax.swing.JTextField();
        m14 = new javax.swing.JTextField();
        m31 = new javax.swing.JTextField();
        m30 = new javax.swing.JTextField();
        m13 = new javax.swing.JTextField();
        m12 = new javax.swing.JTextField();
        m11 = new javax.swing.JTextField();
        m10 = new javax.swing.JTextField();
        m04 = new javax.swing.JTextField();
        m33 = new javax.swing.JTextField();
        m00 = new javax.swing.JTextField();
        m03 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        unlock = new javax.swing.JButton();
        lock = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(153, 102, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel6.setText(" The Playfair Code");

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));

        encrypt.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24));
        encrypt.setText("Encrypt");
        encrypt.setName("crypt"); // NOI18N
        encrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Plain Text :");

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cipher Text :");

        encrypt1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24));
        encrypt1.setText("New PlainText");
        encrypt1.setName("crypt"); // NOI18N
        encrypt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encrypt1ActionPerformed(evt);
            }
        });

        eplain.setColumns(20);
        eplain.setFont(new java.awt.Font("Levenim MT", 1, 18));
        eplain.setRows(5);
        jScrollPane1.setViewportView(eplain);

        ecipher.setColumns(20);
        ecipher.setEditable(false);
        ecipher.setFont(new java.awt.Font("Levenim MT", 1, 18));
        ecipher.setRows(5);
        jScrollPane2.setViewportView(ecipher);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(encrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(encrypt1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encrypt, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encrypt1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Encryption", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        dcipher.setColumns(20);
        dcipher.setFont(new java.awt.Font("Levenim MT", 1, 18));
        dcipher.setRows(5);
        jScrollPane3.setViewportView(dcipher);

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 14));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cipher Text :");

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 14));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Plain Text :");

        dplain.setColumns(20);
        dplain.setEditable(false);
        dplain.setFont(new java.awt.Font("Levenim MT", 1, 18));
        dplain.setRows(5);
        jScrollPane4.setViewportView(dplain);

        encrypt2.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24));
        encrypt2.setText("New CipherText");
        encrypt2.setName("crypt"); // NOI18N
        encrypt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encrypt2ActionPerformed(evt);
            }
        });

        encrypt3.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24));
        encrypt3.setText("Decrypt");
        encrypt3.setName("crypt"); // NOI18N
        encrypt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encrypt3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encrypt3, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(encrypt2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(encrypt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encrypt2, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Decryption", jPanel2);

        jPanel4.setBackground(new java.awt.Color(51, 0, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        m34.setEditable(false);
        m34.setFont(new java.awt.Font("Tahoma", 0, 24));
        m34.setName("mtx34"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KEY :");

        m22.setEditable(false);
        m22.setFont(new java.awt.Font("Tahoma", 0, 24));
        m22.setName("mtx22"); // NOI18N

        m43.setEditable(false);
        m43.setFont(new java.awt.Font("Tahoma", 0, 24));
        m43.setName("mtx43"); // NOI18N

        key.setFont(new java.awt.Font("Tahoma", 0, 24));
        key.setName("key"); // NOI18N

        m21.setEditable(false);
        m21.setFont(new java.awt.Font("Tahoma", 0, 24));
        m21.setName("mtx21"); // NOI18N

        m02.setEditable(false);
        m02.setFont(new java.awt.Font("Tahoma", 0, 24));
        m02.setName("mtx02"); // NOI18N

        m20.setEditable(false);
        m20.setFont(new java.awt.Font("Tahoma", 0, 24));
        m20.setName("mtx20"); // NOI18N

        m01.setEditable(false);
        m01.setFont(new java.awt.Font("Tahoma", 0, 24));
        m01.setName("mtx01"); // NOI18N

        m42.setEditable(false);
        m42.setFont(new java.awt.Font("Tahoma", 0, 24));
        m42.setName("mtx42"); // NOI18N

        m41.setEditable(false);
        m41.setFont(new java.awt.Font("Tahoma", 0, 24));
        m41.setName("mtx41"); // NOI18N

        m44.setEditable(false);
        m44.setFont(new java.awt.Font("Tahoma", 0, 24));
        m44.setName("mtx44"); // NOI18N

        m40.setEditable(false);
        m40.setFont(new java.awt.Font("Tahoma", 0, 24));
        m40.setName("mtx40"); // NOI18N

        m24.setEditable(false);
        m24.setFont(new java.awt.Font("Tahoma", 0, 24));
        m24.setName("mtx24"); // NOI18N

        m23.setEditable(false);
        m23.setFont(new java.awt.Font("Tahoma", 0, 24));
        m23.setName("mtx23"); // NOI18N

        m32.setEditable(false);
        m32.setFont(new java.awt.Font("Tahoma", 0, 24));
        m32.setName("mtx32"); // NOI18N

        m14.setEditable(false);
        m14.setFont(new java.awt.Font("Tahoma", 0, 24));
        m14.setName("mtx14"); // NOI18N

        m31.setEditable(false);
        m31.setFont(new java.awt.Font("Tahoma", 0, 24));
        m31.setName("mtx31"); // NOI18N

        m30.setEditable(false);
        m30.setFont(new java.awt.Font("Tahoma", 0, 24));
        m30.setName("mtx30"); // NOI18N

        m13.setEditable(false);
        m13.setFont(new java.awt.Font("Tahoma", 0, 24));
        m13.setName("mtx13"); // NOI18N

        m12.setEditable(false);
        m12.setFont(new java.awt.Font("Tahoma", 0, 24));
        m12.setName("mtx12"); // NOI18N

        m11.setEditable(false);
        m11.setFont(new java.awt.Font("Tahoma", 0, 24));
        m11.setName("mtx11"); // NOI18N

        m10.setEditable(false);
        m10.setFont(new java.awt.Font("Tahoma", 0, 24));
        m10.setName("mtx10"); // NOI18N

        m04.setEditable(false);
        m04.setFont(new java.awt.Font("Tahoma", 0, 24));
        m04.setName("mtx04"); // NOI18N

        m33.setEditable(false);
        m33.setFont(new java.awt.Font("Tahoma", 0, 24));
        m33.setName("mtx33"); // NOI18N

        m00.setEditable(false);
        m00.setFont(new java.awt.Font("Tahoma", 0, 24));
        m00.setName("mtx00"); // NOI18N

        m03.setEditable(false);
        m03.setFont(new java.awt.Font("Tahoma", 0, 24));
        m03.setName("mtx03"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(key))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(m10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m00, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m20, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m40, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m30, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(m01, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m02, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m03, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m04, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(m11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(m41, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m42, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m43, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m44, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(m21, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m22, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m23, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m24, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(m31, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m32, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m33, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m34, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(key, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(m00, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m20, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(m30, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(m40, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m01, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m02, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m03, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m04, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m21, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m22, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m23, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m24, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m31, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m32, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m33, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m34, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m41, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m42, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m43, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m44, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 0, 102));

        unlock.setFont(new java.awt.Font("Tahoma", 0, 14));
        unlock.setText("New Key");
        unlock.setName("unlock"); // NOI18N
        unlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unlockActionPerformed(evt);
            }
        });

        lock.setFont(new java.awt.Font("Tahoma", 0, 14));
        lock.setText("Lock Key");
        lock.setName("lock"); // NOI18N
        lock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton1.setText("Clear all");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lock, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(unlock, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lock)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(unlock))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(394, 394, 394))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel6)
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        jMenuBar1.setFont(new java.awt.Font("Rod", 1, 18));

        jMenu1.setText("File");

        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Tutorial");

        jMenuItem4.setText("Theory");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem5.setText("Playfair Enciphering");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem6.setText("The Source Code");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1199, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    private void encryptActionPerformed(java.awt.event.ActionEvent evt) {
        KP KodePlayfair = new KP();
        String a = key.getText();

        int matrik[][] = KodePlayfair.inputMatrik(a);

        //show matrik
        for (int i = 0; i < matrik.length; i++) {
            for (int j = 0; j < matrik.length; j++) {
                //System.out.print(matrik[i][j]+" ");
                System.out.print(KodePlayfair.ConvertToWord(matrik[i][j]) + " ");
            }
            System.out.println("");

        }

        String plain = eplain.getText();
        //olah data inputan
        String ptext = KodePlayfair.olahInputan(plain);
        String b = KodePlayfair.chipperText(ptext, matrik);

        ecipher.setText(b);
        // TODO add your handling code here:
}

    private void encrypt1ActionPerformed(java.awt.event.ActionEvent evt) {
        eplain.setText(null);
        ecipher.setText(null);
        // TODO add your handling code here:
}

    private void encrypt2ActionPerformed(java.awt.event.ActionEvent evt) {

        dplain.setText(null);
        dcipher.setText(null);
        // TODO add your handling code here:
}

    private void encrypt3ActionPerformed(java.awt.event.ActionEvent evt) {
        KP KodePlayfair = new KP();
        String a = key.getText();

        int matrik[][] = KodePlayfair.inputMatrik(a);

        //show matrik
        for (int i = 0; i < matrik.length; i++) {
            for (int j = 0; j < matrik.length; j++) {
                //System.out.print(matrik[i][j]+" ");
                System.out.print(KodePlayfair.ConvertToWord(matrik[i][j]) + " ");
            }
            System.out.println("");

        }

        String plain = dcipher.getText();
        //olah data inputan
        String ptext = KodePlayfair.olahInputan(plain);
        String g = KodePlayfair.plaintText(ptext, matrik);

        dplain.setText(g);
        // TODO add your handling code here:
    }

    private void unlockActionPerformed(java.awt.event.ActionEvent evt) {
        key.setText(null);
        //matriks baris 1
        m00.setText("");
        m01.setText("");
        m02.setText("");
        m03.setText("");
        m04.setText("");
        //matriks baris 2
        m10.setText("");
        m11.setText("");
        m12.setText("");
        m13.setText("");
        m14.setText("");

        //matriks baris 3
        m20.setText("");
        m21.setText("");
        m22.setText("");
        m23.setText("");
        m24.setText("");
        //matriks baris 4
        m30.setText("");
        m31.setText("");
        m32.setText("");
        m33.setText("");
        m34.setText("");
        //matriks baris 5
        m40.setText("");
        m41.setText("");
        m42.setText("");
        m43.setText("");
        m44.setText("");
        // TODO add your handling code here:
}

    private void lockActionPerformed(java.awt.event.ActionEvent evt) {

        String keytext=key.getText();
        String keya="";

        for(int i=0;i<keytext.length();i++){
        String text1=(keytext.substring(i,i+1));
        if(text1.equals(" ")==false){
            keya=keya+text1;
        }
        }

        KP KodePlayfair = new KP();
        String a = KodePlayfair.KataKunci(keya);



        int matrik[][] = KodePlayfair.inputMatrik(a);

        //show matrik
        for (int i = 0; i < matrik.length; i++) {
            for (int j = 0; j < matrik.length; j++) {
                //System.out.print(matrik[i][j]+" ");
                System.out.print(KodePlayfair.ConvertToWord(matrik[i][j]) + " ");
            }
            System.out.println("");

        }
        //matriks baris 1
        m00.setText("" + KodePlayfair.ConvertToWord(matrik[0][0]));
        m01.setText("" + KodePlayfair.ConvertToWord(matrik[0][1]));
        m02.setText("" + KodePlayfair.ConvertToWord(matrik[0][2]));
        m03.setText("" + KodePlayfair.ConvertToWord(matrik[0][3]));
        m04.setText("" + KodePlayfair.ConvertToWord(matrik[0][4]));
        //matriks baris 2
        m10.setText("" + KodePlayfair.ConvertToWord(matrik[1][0]));
        m11.setText("" + KodePlayfair.ConvertToWord(matrik[1][1]));
        m12.setText("" + KodePlayfair.ConvertToWord(matrik[1][2]));
        m13.setText("" + KodePlayfair.ConvertToWord(matrik[1][3]));
        m14.setText("" + KodePlayfair.ConvertToWord(matrik[1][4]));

        //matriks baris 3
        m20.setText("" + KodePlayfair.ConvertToWord(matrik[2][0]));
        m21.setText("" + KodePlayfair.ConvertToWord(matrik[2][1]));
        m22.setText("" + KodePlayfair.ConvertToWord(matrik[2][2]));
        m23.setText("" + KodePlayfair.ConvertToWord(matrik[2][3]));
        m24.setText("" + KodePlayfair.ConvertToWord(matrik[2][4]));
        //matriks baris 4
        m30.setText("" + KodePlayfair.ConvertToWord(matrik[3][0]));
        m31.setText("" + KodePlayfair.ConvertToWord(matrik[3][1]));
        m32.setText("" + KodePlayfair.ConvertToWord(matrik[3][2]));
        m33.setText("" + KodePlayfair.ConvertToWord(matrik[3][3]));
        m34.setText("" + KodePlayfair.ConvertToWord(matrik[3][4]));
        //matriks baris 5
        m40.setText("" + KodePlayfair.ConvertToWord(matrik[4][0]));
        m41.setText("" + KodePlayfair.ConvertToWord(matrik[4][1]));
        m42.setText("" + KodePlayfair.ConvertToWord(matrik[4][2]));
        m43.setText("" + KodePlayfair.ConvertToWord(matrik[4][3]));
        m44.setText("" + KodePlayfair.ConvertToWord(matrik[4][4]));



    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        key.setText(null);
        dplain.setText(null);
        dcipher.setText(null);
        eplain.setText(null);
        ecipher.setText(null);
        //matriks baris 1
        m00.setText("");
        m01.setText("");
        m02.setText("");
        m03.setText("");
        m04.setText("");
        //matriks baris 2
        m10.setText("");
        m11.setText("");
        m12.setText("");
        m13.setText("");
        m14.setText("");

        //matriks baris 3
        m20.setText("");
        m21.setText("");
        m22.setText("");
        m23.setText("");
        m24.setText("");
        //matriks baris 4
        m30.setText("");
        m31.setText("");
        m32.setText("");
        m33.setText("");
        m34.setText("");
        //matriks baris 5
        m40.setText("");
        m41.setText("");
        m42.setText("");
        m43.setText("");
        m44.setText("");
        // TODO add your handling code here:




        // TODO add your handling code here:
}

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
        // TODO add your handling code here:
}

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
        // TODO add your handling code here:
}

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {
        new OldStory().setVisible(true);
        // TODO add your handling code here:
}

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {
        new Tutorial().setVisible(true);
        // TODO add your handling code here:
}

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {
        new src().setVisible(true);
        this.hide();
        // TODO add your handling code here:
}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayFair().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextArea dcipher;
    private javax.swing.JTextArea dplain;
    private javax.swing.JTextArea ecipher;
    private javax.swing.JButton encrypt;
    private javax.swing.JButton encrypt1;
    private javax.swing.JButton encrypt2;
    private javax.swing.JButton encrypt3;
    private javax.swing.JTextArea eplain;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField key;
    private javax.swing.JButton lock;
    private javax.swing.JTextField m00;
    private javax.swing.JTextField m01;
    private javax.swing.JTextField m02;
    private javax.swing.JTextField m03;
    private javax.swing.JTextField m04;
    private javax.swing.JTextField m10;
    private javax.swing.JTextField m11;
    private javax.swing.JTextField m12;
    private javax.swing.JTextField m13;
    private javax.swing.JTextField m14;
    private javax.swing.JTextField m20;
    private javax.swing.JTextField m21;
    private javax.swing.JTextField m22;
    private javax.swing.JTextField m23;
    private javax.swing.JTextField m24;
    private javax.swing.JTextField m30;
    private javax.swing.JTextField m31;
    private javax.swing.JTextField m32;
    private javax.swing.JTextField m33;
    private javax.swing.JTextField m34;
    private javax.swing.JTextField m40;
    private javax.swing.JTextField m41;
    private javax.swing.JTextField m42;
    private javax.swing.JTextField m43;
    private javax.swing.JTextField m44;
    private javax.swing.JButton unlock;
    // End of variables declaration

}
